version: '3'

services:
  ssc1:
    container_name: ssc1
    image: "sscd:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - KEYNAME=mykey1
      - CHAINID=ssc-1
      - MONIKER=localtestnet
      - KEYRING=file # remember to change to other types of keyring like 'file' in-case exposing to outside world, otherwise your balance will be wiped quickly. The keyring test does not require private key to steal tokens from you
      - KEYALGO=secp256k1
      - KEYPASSWD="passw0rdK3y"
      - LOGLEVEL=info
      - TRACE=""
      - SLEEPTIME=5
      - EXTERNAL_ADDRESS=192.168.10.6
      - NODE_MNEMONIC=gun trend outer deputy guitar salt unlock thrive soccer accuse siren seven boat spike cook dirt eagle control panther phrase promote powder grit news
      - VALIDATOR_MNEMONIC=category boil mandate twenty process either swear poverty project word leave clutch idle park foot jazz wood custom limb bean wild bar extend jacket
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3BUCKET=s3://saga-staking-chain/ssc/gentx
      - QUORUM_COUNT=2
      - VALIDATOR_ADDRESSES=saga1774satl07a5tpy2rsmn36dmvt8jk8l7ece5q7k saga1c6y7npptc05alqnvgaa3aefq0pc7txvwmgd9ml
      - CURRENT_VALIDATOR_ADDRESS=saga1774satl07a5tpy2rsmn36dmvt8jk8l7ece5q7k
    networks:
      localnet:
        ipv4_address: 192.168.10.6

  ssc2:
    container_name: ssc2
    image: "sscd:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - KEYNAME=mykey2
      - CHAINID=ssc-1
      - MONIKER=localtestnet
      - KEYRING=file # remember to change to other types of keyring like 'file' in-case exposing to outside world, otherwise your balance will be wiped quickly. The keyring test does not require private key to steal tokens from you
      - KEYALGO=secp256k1
      - KEYPASSWD="passw0rdK3y"
      - LOGLEVEL=info
      - TRACE=""
      - SLEEPTIME=5
      - EXTERNAL_ADDRESS=192.168.10.7
      - NODE_MNEMONIC=abandon strategy behind mass taste thing flash wonder clay extend thing mutual region balcony estate object glove ozone news service letter output list rich
      - VALIDATOR_MNEMONIC=between render sadness assist quick copy job uphold step match frozen sudden chronic bounce citizen shiver glory travel young speed silly saddle orbit galaxy
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3BUCKET=s3://saga-staking-chain/ssc/gentx
      - QUORUM_COUNT=2
      - VALIDATOR_ADDRESSES=saga1774satl07a5tpy2rsmn36dmvt8jk8l7ece5q7k saga1c6y7npptc05alqnvgaa3aefq0pc7txvwmgd9ml
      - CURRENT_VALIDATOR_ADDRESS=saga1c6y7npptc05alqnvgaa3aefq0pc7txvwmgd9ml
    networks:
      localnet:
        ipv4_address: 192.168.10.7
    
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16